const images = {
  ready: require("../../Images/your-app.png"),
  api: require("../../Images/Icons/icon-api-testing.png"),
  components: require("../../Images/Icons/icon-components.png"),
  deviceInfo: require("../../Images/Icons/icon-device-information.png"),
  faq: require("../../Images/Icons/faq-icon.png"),
  home: require("../../Images/Icons/icon-home.png"),
  theme: require("../../Images/Icons/icon-theme.png"),
  usageExamples: require("../../Images/Icons/icon-usage-examples.png"),
  chevronRight: require("../../Images/Icons/chevron-right.png"),
  hamburger: require("../../Images/Icons/hamburger.png"),
  backButton: require("../../Images/Icons/back-button.png"),
  closeButton: require("../../Images/Icons/close-button.png"),

  ic_back: require("../../Images/ic_back.png"),
  like_gif: require("../../Images/like.gif"),
  like_static: require("../../Images/ic_like.png"),
  like_static_fill: require("../../Images/ic_like_fill.png"),
  love_gif: require("../../Images/love.gif"),
  love_static: require("../../Images/love2.png"),
  haha_gif: require("../../Images/haha.gif"),
  haha_static: require("../../Images/haha2.png"),
  wow_gif: require("../../Images/wow.gif"),
  wow_static: require("../../Images/wow2.png"),
  sad_gif: require("../../Images/sad.gif"),
  sad_static: require("../../Images/sad2.png"),
  angry_gif: require("../../Images/angry.gif"),
  angry_static: require("../../Images/angry2.png"),
  love_face: require("../../assets/Reactions/Love.png"),
  happy_face: require("../../assets/Reactions/Happy.png"),
  wow_face: require("../../assets/Reactions/Wow.png"),
  angry_face: require("../../assets/Reactions/Angry.png"),
  sad_face: require("../../assets/Reactions/Sad.png"),
  afraid_face: require("../../assets/Reactions/Afraid.png"),
  afraid_eyes: require("../../assets/Reactions/afraid_eyes.png"),
  angry_eyes: require("../../assets/Reactions/angry_eyes.png"),
  love_eyes: require("../../assets/Reactions/love_eyes.png"),
  happy_eyes: require("../../assets/Reactions/happy_eyes.png"),
  sad_eyes: require("../../assets/Reactions/sad_eyes.png"),
  wow_eyes: require("../../assets/Reactions/wow_eyes.png"),
  iris: require("../../assets/iris.png"),
  background: require("../../assets/background.jpeg"),
  cart: require("../../assets/cart.png"),
  giftbag: require("../../assets/gift-bag.png"),
  bg1: require("../../assets/bg1.png"),
};

export default images;
